
- name: Set git configs
  shell: |
     git config --global user.email '{{ item }}@gmail.com'
     git config --global user.name '{{ item }}'
  with_items:
    # --extra-vars=user: cognetizen
    - '{{ user }}'

- name: Ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory

- name: Ensure .ssh config exists
  file:
    path: ~/.ssh/config
    state: touch

- name: Copy private ssh key (for public identity)
  template:
    src: id_rsa_{{ item }}
    dest: ~/.ssh/id_rsa_{{ item }}
    mode: 0600
  with_items:
    # Todo: Change this so that the username is a variable at the top level ...
    - cognetizen

- name: Link ssh key to id_rsa (not sure why this needs to be done.)
  file:
    path: ~/.ssh/id_rsa
    src: ~/.ssh/id_rsa_{{ item }}
    state: link
  with_items:
    # Todo: Change this so that the username is a variable at the top level ...
    - cognetizen

- name: Build ssh config file
  blockinfile:
    dest: ~/.ssh/config
    block: |
      #user - {{ item }}
      Host github.com-{{ item }}
          HostName github.com
          User git
          IdentityFile ~/.ssh/id_rsa_{{ item }} 
  with_items:
    - cognetizen

- name: Clone ssh version of git repo
  command: git clone git@github.com:cognitiaclaeves/{{ repo }}.git ~/{{ repo }}-git

- name: rm https repo
  command: rm -rf ~/{{ repo }}
  # failed_when: no
  ignore_errors: yes
  # Ripping current directory out from underneath ansible

- name: mv git repo
  command: mv ~/{{ repo }}-git ~


#- name: Copy ssh config
#  template:
#    src: ssh_config
#    dest: ~/.ssh/config

