
- name: Set git configs
  shell: |
     git config --global user.email '{{ item }}@gmail.com'
     git config --global user.name '{{ item }}'
  with_items:
    # run playbook with -e user=cognetizen
    - '{{ user }}'

- name: Ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory

- name: Ensure .ssh config exists
  file:
    path: ~/.ssh/config
    state: touch

- name: Copy private ssh key (for public identity)
  template:
    src: id_rsa_{{ item }}
    dest: ~/.ssh/id_rsa_{{ item }}
    mode: 0600
  with_items:
    - '{{ user }}'

- name: Link ssh key to id_rsa (not sure why this needs to be done.)
  file:
    path: ~/.ssh/id_rsa
    src: ~/.ssh/id_rsa_{{ item }}
    state: link
  with_items:
    - '{{ user }}'

- name: Build ssh config file
  blockinfile:
    dest: ~/.ssh/config
    block: |
      #user - {{ item }}
      Host github.com-{{ item }}
          HostName github.com
          User git
          IdentityFile ~/.ssh/id_rsa_{{ item }} 
  with_items:
    - '{{ user }}'

- name: Clone ssh version of git repo
  command: git clone git@github.com:cognitiaclaeves/{{ repo }}.git ~/{{ repo }}

- name: Copy secret
  command: mv ~/{{ repo }}-https/{{ vault_path }} ~/{{ repo }}/{{ vault_path }}

- name: rm https repo
  command: rm -rf ~/{{ repo }}-https
  # failed_when: no - Still fails when it errors
  ignore_errors: yes
  # Ripping current directory out from underneath ansible
  # After this happens, the ansible cannot continue

